[package]
name = "rs_lib"
version = "0.0.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "=0.2.125"
js-sys = "0.3.102"
ibe = {version = "0.3.0", features = ["cgwkv"]}
rand = "0.8.4"
getrandom = { version = "0.2.7", features = ["js"] }
pg-curve = { version = "0.2.0", features = [
  "alloc",
  "group",
  "pairings"
] }
group = "0.13.0"
serde = "1.0.140"
base64 = "0.22.1"
subtle = "2.4.1"
serde-wasm-bindgen = "0.6.5"
