name: CI
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Install Deno
        uses: denoland/setup-deno@v2

      - name: Build step
        run: "deno task build"
