name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Check Wasm up-to-date
        run: deno task wasmbuild --check

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "time-sign"
          entrypoint: "./server.ts"
